### ISSUE TITLE
Many tests fail: No such file or directory: '/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/switch-nested.m'

### ISSUE THREAD

**Issue by yurivict** [Smattr/rumur#238]
```
======================================================================
ERROR: test_while_stmt1_m (__main__.rumurSingleThreadedXML)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 576, in <lambda>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 502, in _run
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in _run_param
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in <dictcomp>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 48, in parse_test_options
FileNotFoundError: [Errno 2] No such file or directory: '/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/while-stmt1.m'

======================================================================
ERROR: test_while_stmt2_m (__main__.rumurSingleThreadedXML)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 576, in <lambda>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 502, in _run
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in _run_param
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in <dictcomp>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 48, in parse_test_options
FileNotFoundError: [Errno 2] No such file or directory: '/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/while-stmt2.m'

======================================================================
ERROR: test_while_stmt3_m (__main__.rumurSingleThreadedXML)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 576, in <lambda>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 502, in _run
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in _run_param
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in <dictcomp>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 48, in parse_test_options
FileNotFoundError: [Errno 2] No such file or directory: '/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/while-stmt3.m'

======================================================================
ERROR: test_while_stmt4_m (__main__.rumurSingleThreadedXML)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 576, in <lambda>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 502, in _run
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in _run_param
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in <dictcomp>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 48, in parse_test_options
FileNotFoundError: [Errno 2] No such file or directory: '/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/while-stmt4.m'

======================================================================
ERROR: test_while_stmt5_m (__main__.rumurSingleThreadedXML)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 576, in <lambda>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 502, in _run
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in _run_param
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in <dictcomp>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 48, in parse_test_options
FileNotFoundError: [Errno 2] No such file or directory: '/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/while-stmt5.m'

======================================================================
ERROR: test_write_out_of_range2_m (__main__.rumurSingleThreadedXML)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 576, in <lambda>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 502, in _run
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in _run_param
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in <dictcomp>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 48, in parse_test_options
FileNotFoundError: [Errno 2] No such file or directory: '/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/write-out-of-range2.m'

======================================================================
ERROR: test_write_out_of_range3_m (__main__.rumurSingleThreadedXML)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 576, in <lambda>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 502, in _run
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in _run_param
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in <dictcomp>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 48, in parse_test_options
FileNotFoundError: [Errno 2] No such file or directory: '/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/write-out-of-range3.m'

======================================================================
ERROR: test_write_out_of_range_m (__main__.rumurSingleThreadedXML)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 576, in <lambda>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 502, in _run
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in _run_param
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in <dictcomp>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 48, in parse_test_options
FileNotFoundError: [Errno 2] No such file or directory: '/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/write-out-of-range.m'

======================================================================
ERROR: test_xml_escape_increment_m (__main__.rumurSingleThreadedXML)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 576, in <lambda>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 502, in _run
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in _run_param
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in <dictcomp>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 48, in parse_test_options
FileNotFoundError: [Errno 2] No such file or directory: '/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/xml-escape-increment.m'

======================================================================
ERROR: test_xor_mixed_m (__main__.rumurSingleThreadedXML)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 576, in <lambda>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 502, in _run
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in _run_param
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 391, in <dictcomp>
  File "/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/run-tests.py", line 48, in parse_test_options
FileNotFoundError: [Errno 2] No such file or directory: '/disk-samsung/freebsd-ports/math/rumur/work/rumur-2022.08.20/tests/xor-mixed.m'

----------------------------------------------------------------------
Ran 5344 tests in 392.902s

FAILED (errors=3345, skipped=382)
```

Version: 2022.08.20
clang-14
FreeBSD 13.1

**Comment by Smattr** [comment]
Thanks for reporting, Yuri. Can you point me to the steps you're using to run the test suite? The v2022.08.20 release passed CI on FreeBSD 13.0 with Clang 13. We don't specifically test FreeBSD 13.1 with Clang 14, but I doubt the above is toolchain specific.

**Comment by yurivict** [comment]
[Here](https://cgit.freebsd.org/ports/tree/math/rumur/Makefile#n28).

**Comment by Smattr** [comment]
Surely this needs to do the CMake configure and the CMake build step somewhere prior to this? Or is that figured out automatically by the FreeBSD ports system?

**Comment by yurivict** [comment]
This is run on top of the build.

**Comment by Smattr** [comment]
Is it possible the checkout/clone of the repository failed and was not detected? The test suite does some dynamic stuff, but the errors here look like pretty basic missing static files. E.g. the last one, tests/xor-mixed.m is clearly present in the repository. Can you confirm this is reproducible when rerunning the work flow?

**Comment by yurivict** [comment]
> Is it possible the checkout/clone of the repository failed and was not detected?

No, this is impossible. I just verified.

**Comment by yurivict** [comment]
Tests pass when I reran build/tests.

I am not sure what happened the first time. Perhaps cosmic rays got involved. -)

Sorry for the noise!

**Comment by Smattr** [comment]
No problem. Glad it's solved! And thank you again for packaging Rumur!
